name: context_storage
description: A widget for creating a key-value storage in the widget tree, accessible to child widgets through the InheritedWidget mechanism.
version: 1.0.0
author: Andy Chentsov
homepage: https://github.com/andyduke/context_storage/tree/master/package
repository: https://github.com/andyduke/context_storage
issues: https://github.com/andyduke/context_storage/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
